CREATE TABLE USERS
(
    U_ID NUMBER(*) PRIMARY KEY NOT NULL,
    U_LOGIN VARCHAR2(20) NOT NULL,
    U_EMAIL VARCHAR2(30) NOT NULL,
    U_PASSWORD VARCHAR2(32) NOT NULL,
    U_FIRST_NAME VARCHAR2(20),
    U_LAST_NAME VARCHAR2(20)
);
CREATE UNIQUE INDEX USERS_U_LOGIN_UINDEX ON USERS (U_LOGIN);
CREATE UNIQUE INDEX USERS_U_EMAIL_UINDEX ON USERS (U_EMAIL);
CREATE SEQUENCE  U_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
create or replace
TRIGGER users_on_insert
  BEFORE INSERT ON USERS
  FOR EACH ROW
BEGIN
  SELECT U_ID_SEQ.nextval
  INTO :new.U_ID
  FROM dual;
END;